schema_version = "1.0.0"

id = "cjfit"
version = "1.0.0"
name = "CJFIT"
tagline = "Cylindrical Jig Fit Test"
maintainer = "Emanuele Messina <emanuelemessina.em@gmail.com>"
type = "add-on"

website = "https://github.com/emanuelemessina/cjfit/"

tags = ["3D View"]

blender_version_min = "4.2.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = [
    "SPDX:MIT",
]
copyright = [
    "2024 Emanuele Messina"
]

platforms = ["macos-x64", "macos-arm64", "linux-x64", "windows-x64"]

wheels = [
    "./wheels/311/scikit_learn-1.5.2-cp311-cp311-macosx_10_9_x86_64.whl",
    "./wheels/311/scikit_learn-1.5.2-cp311-cp311-macosx_12_0_arm64.whl",
    "./wheels/311/scikit_learn-1.5.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    "./wheels/311/scikit_learn-1.5.2-cp311-cp311-win_amd64.whl",
    "./wheels/311/scipy-1.14.1-cp311-cp311-macosx_10_13_x86_64.whl",
    "./wheels/311/scipy-1.14.1-cp311-cp311-macosx_12_0_arm64.whl",
    "./wheels/311/scipy-1.14.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    "./wheels/311/scipy-1.14.1-cp311-cp311-win_amd64.whl",
    "./wheels/joblib-1.4.2-py3-none-any.whl",
    "./wheels/threadpoolctl-3.5.0-py3-none-any.whl"
]

# https://docs.blender.org/manual/en/dev/advanced/extensions/command_line_arguments.html#command-line-args-extension-build
[build]
paths_exclude_pattern = [
    "__pycache__/"
]